namespace VStore.Services;

public interface ILocalizer
{
    string Lang { get; }
    string this[string key] { get; }
}

public class Localizer(IHttpContextAccessor accessor) : ILocalizer
{
    public static readonly string[] Langs = { "ru", "uk", "en" };

    public string Lang
    {
        get
        {
            var v = accessor.HttpContext?.Request.Cookies["lang"];
            return Langs.Contains(v) ? v! : "ru";
        }
    }

    public string this[string key]
    {
        get
        {
            if (!Dict.TryGetValue(key, out var row)) return key;
            var idx = Array.IndexOf(Langs, Lang);
            return row[idx < 0 ? 0 : idx];
        }
    }

    static readonly Dictionary<string, string[]> Dict = new()
    {
        ["nav_store"] = new[] { "Обзор", "Огляд", "Store" },
        ["nav_support"] = new[] { "Поддержка", "Підтримка", "Support" },
        ["nav_news"] = new[] { "Новости", "Новини", "News" },
        ["nav_library"] = new[] { "Библиотека", "Бібліотека", "Library" },
        ["nav_admin"] = new[] { "Админка", "Адмінка", "Admin" },
        ["search_placeholder"] = new[] { "Поиск игр", "Пошук ігор", "Search games" },
        ["wishlist"] = new[] { "Список желаемого", "Список бажань", "Wishlist" },
        ["cart"] = new[] { "Корзина", "Кошик", "Cart" },
        ["login"] = new[] { "Войти", "Увійти", "Log in" },
        ["logout"] = new[] { "Выйти", "Вийти", "Log out" },
        ["download"] = new[] { "Скачать", "Завантажити", "Download" },
        ["profile"] = new[] { "Профиль", "Профіль", "Profile" },
        ["all_genres"] = new[] { "Все", "Всі", "All" },
        ["home_title"] = new[] { "Рекомендуемое и популярное", "Рекомендоване й популярне", "Featured and popular" },
        ["home_specials"] = new[] { "Специальные предложения", "Спеціальні пропозиції", "Special offers" },
        ["home_newreleases"] = new[] { "Новинки", "Новинки", "New releases" },
        ["home_free"] = new[] { "Бесплатные игры", "Безкоштовні ігри", "Free games" },
        ["home_topsellers"] = new[] { "Хиты продаж", "Хіти продажів", "Top sellers" },
        ["home_search_results"] = new[] { "Результаты поиска", "Результати пошуку", "Search results" },
        ["home_nothing_found"] = new[] { "Ничего не найдено. Попробуйте изменить запрос.", "Нічого не знайдено. Спробуйте змінити запит.", "Nothing found. Try a different search." },
        ["game_about"] = new[] { "Об игре", "Про гру", "About the game" },
        ["game_reqs"] = new[] { "Системные требования", "Системні вимоги", "System requirements" },
        ["game_reqs_min"] = new[] { "Минимальные", "Мінімальні", "Minimum" },
        ["game_reqs_rec"] = new[] { "Рекомендуемые", "Рекомендовані", "Recommended" },
        ["game_achievements"] = new[] { "Достижения", "Досягнення", "Achievements" },
        ["game_reviews"] = new[] { "Отзывы покупателей", "Відгуки покупців", "Customer reviews" },
        ["game_add_to_cart"] = new[] { "В корзину", "У кошик", "Add to cart" },
        ["game_go_to_cart"] = new[] { "Перейти в корзину", "Перейти до кошика", "Go to cart" },
        ["game_already_in_library"] = new[] { "Уже в библиотеке", "Вже в бібліотеці", "Already owned" },
        ["game_login_to_buy"] = new[] { "Войдите, чтобы купить", "Увійдіть, щоб купити", "Log in to buy" },
        ["game_add_wishlist"] = new[] { "В желаемое", "До бажаного", "Add to wishlist" },
        ["game_remove_wishlist"] = new[] { "Убрать из желаемого", "Прибрати з бажаного", "Remove from wishlist" },
        ["game_recommend"] = new[] { "Рекомендую", "Рекомендую", "Recommend" },
        ["game_not_recommend"] = new[] { "Не рекомендую", "Не рекомендую", "Not recommended" },
        ["game_publish"] = new[] { "Опубликовать", "Опублікувати", "Publish" },
        ["account_login_title"] = new[] { "Вход", "Вхід", "Log in" },
        ["account_login_label"] = new[] { "Войти с именем аккаунта или почтой", "Увійти за іменем акаунта або поштою", "Sign in with account name or email" },
        ["account_password_label"] = new[] { "Пароль", "Пароль", "Password" },
        ["account_remember"] = new[] { "Запомнить меня", "Запам'ятати мене", "Remember me" },
        ["account_login_btn"] = new[] { "Войти", "Увійти", "Log in" },
        ["account_no_account"] = new[] { "Нет аккаунта?", "Немає акаунта?", "No account?" },
        ["account_create_new"] = new[] { "Создать новый", "Створити новий", "Create one" },
        ["account_forgot"] = new[] { "Забыли пароль?", "Забули пароль?", "Forgot password?" },
        ["account_or"] = new[] { "или", "або", "or" },
        ["account_google"] = new[] { "Войти через Google", "Увійти через Google", "Continue with Google" },
        ["account_register_title"] = new[] { "Создать аккаунт", "Створити акаунт", "Create account" },
        ["account_nickname_label"] = new[] { "Игровое имя", "Ігрове ім'я", "Nickname" },
        ["account_email_label"] = new[] { "Электронная почта", "Електронна пошта", "Email" },
        ["account_accept_terms"] = new[] { "Мне исполнилось 13 лет, и я принимаю условия соглашения подписчика и политику конфиденциальности", "Мені виповнилося 13 років, і я приймаю умови угоди та політику конфіденційності", "I am 13 or older and accept the subscriber agreement and privacy policy" },
        ["account_register_btn"] = new[] { "Создать аккаунт", "Створити акаунт", "Create account" },
        ["account_have_account"] = new[] { "Уже есть аккаунт?", "Вже є акаунт?", "Already have an account?" },
        ["account_created_title"] = new[] { "Аккаунт создан!", "Акаунт створено!", "Account created!" },
        ["account_created_text"] = new[] { "Аккаунт был успешно создан.", "Акаунт успішно створено.", "Your account has been created." },
        ["forgot_title"] = new[] { "Восстановление пароля", "Відновлення пароля", "Reset password" },
        ["forgot_text"] = new[] { "Укажите почту, привязанную к аккаунту, и мы сформируем ссылку для сброса пароля.", "Вкажіть пошту, прив'язану до акаунта, і ми сформуємо посилання для скидання пароля.", "Enter the email linked to your account and we'll generate a reset link." },
        ["forgot_send"] = new[] { "Получить ссылку", "Отримати посилання", "Get reset link" },
        ["forgot_back"] = new[] { "Вернуться ко входу", "Повернутися до входу", "Back to login" },
        ["forgot_sent_title"] = new[] { "Ссылка сформирована", "Посилання сформовано", "Reset link ready" },
        ["forgot_sent_text"] = new[] { "Письмо со ссылкой для сброса пароля отправлено на вашу почту.", "Лист із посиланням для скидання пароля надіслано на вашу пошту.", "An email with a password reset link has been sent to your inbox." },
        ["reset_title"] = new[] { "Новый пароль", "Новий пароль", "New password" },
        ["reset_new_password"] = new[] { "Новый пароль", "Новий пароль", "New password" },
        ["reset_save"] = new[] { "Сохранить пароль", "Зберегти пароль", "Save password" },
        ["reset_invalid"] = new[] { "Ссылка недействительна или устарела.", "Посилання недійсне або застаріле.", "This link is invalid or has expired." },
        ["reset_done_title"] = new[] { "Пароль изменён", "Пароль змінено", "Password changed" },
        ["reset_done_text"] = new[] { "Теперь вы можете войти с новым паролем.", "Тепер ви можете увійти з новим паролем.", "You can now log in with your new password." },
        ["profile_level"] = new[] { "Уровень", "Рівень", "Level" },
        ["profile_games"] = new[] { "Игры", "Ігри", "Games" },
        ["profile_achievements"] = new[] { "Достижения", "Досягнення", "Achievements" },
        ["profile_show_all"] = new[] { "Показать все", "Показати всі", "Show all" },
        ["profile_collection"] = new[] { "Коллекция игр", "Колекція ігор", "Game collection" },
        ["profile_empty"] = new[] { "Библиотека пуста. Загляните в магазин.", "Бібліотека порожня. Загляньте до магазину.", "Your library is empty. Check out the store." },
        ["library_title"] = new[] { "Библиотека игр", "Бібліотека ігор", "Game library" },
        ["library_search"] = new[] { "Поиск по библиотеке", "Пошук у бібліотеці", "Search your library" },
        ["library_empty"] = new[] { "У вас пока нет игр.", "У вас поки немає ігор.", "You don't own any games yet." },
        ["library_hours"] = new[] { "Наиграно", "Награно", "Playtime" },
        ["library_play"] = new[] { "Играть", "Грати", "Play" },
        ["cart_title"] = new[] { "Моя корзина", "Мій кошик", "My cart" },
        ["cart_empty"] = new[] { "Корзина пуста.", "Кошик порожній.", "Your cart is empty." },
        ["cart_go_store"] = new[] { "Перейти в магазин", "Перейти до магазину", "Go to store" },
        ["cart_remove"] = new[] { "Удалить", "Видалити", "Remove" },
        ["cart_to_wishlist"] = new[] { "В желаемое", "До бажаного", "Move to wishlist" },
        ["cart_total"] = new[] { "Итого", "Разом", "Total" },
        ["cart_checkout"] = new[] { "Оформить заказ", "Оформити замовлення", "Checkout" },
        ["checkout_title"] = new[] { "Оплата", "Оплата", "Payment" },
        ["checkout_card"] = new[] { "Банковская карта", "Банківська картка", "Bank card" },
        ["checkout_wallet"] = new[] { "Кошелёк V", "Гаманець V", "V Wallet" },
        ["checkout_card_number"] = new[] { "Номер карты", "Номер картки", "Card number" },
        ["checkout_holder"] = new[] { "Имя владельца", "Ім'я власника", "Cardholder name" },
        ["checkout_expiry"] = new[] { "Срок действия", "Термін дії", "Expiry date" },
        ["checkout_cvv"] = new[] { "CVV", "CVV", "CVV" },
        ["checkout_pay"] = new[] { "Оплатить", "Оплатити", "Pay" },
        ["checkout_order"] = new[] { "Ваш заказ", "Ваше замовлення", "Your order" },
        ["success_title"] = new[] { "Спасибо за покупку!", "Дякуємо за покупку!", "Thanks for your purchase!" },
        ["success_text"] = new[] { "Игры добавлены в вашу библиотеку.", "Ігри додано до вашої бібліотеки.", "The games were added to your library." },
        ["success_go_profile"] = new[] { "Перейти в профиль", "Перейти до профілю", "Go to profile" },
        ["wishlist_title"] = new[] { "Мой список желаемого", "Мій список бажань", "My wishlist" },
        ["wishlist_empty"] = new[] { "Список пуст.", "Список порожній.", "Your wishlist is empty." },
        ["wishlist_added"] = new[] { "Добавлено", "Додано", "Added" },
        ["wishlist_in_cart"] = new[] { "В корзине", "У кошику", "In cart" },
        ["wishlist_to_cart"] = new[] { "В корзину", "У кошик", "Add to cart" },
        ["news_title"] = new[] { "Актуальные новости", "Актуальні новини", "Latest news" },
        ["support_title"] = new[] { "Поддержка", "Підтримка", "Support" },
        ["support_search"] = new[] { "Найти помощь", "Знайти допомогу", "Search help" },
        ["support_questions_left"] = new[] { "Остались вопросы?", "Залишилися питання?", "Still have questions?" },
        ["support_contact_email"] = new[] { "Написать нам на почту", "Написати нам на пошту", "Email us" },
        ["support_form_title"] = new[] { "Написать в поддержку", "Написати до підтримки", "Contact support" },
        ["support_name"] = new[] { "Имя", "Ім'я", "Name" },
        ["support_email"] = new[] { "Почта для ответа", "Пошта для відповіді", "Reply email" },
        ["support_subject"] = new[] { "Тема обращения", "Тема звернення", "Subject" },
        ["support_message"] = new[] { "Сообщение", "Повідомлення", "Message" },
        ["support_send"] = new[] { "Отправить обращение", "Надіслати звернення", "Send ticket" },
        ["support_sent"] = new[] { "Обращение отправлено. Мы ответим вам на почту.", "Звернення надіслано. Ми відповімо на пошту.", "Ticket sent. We'll reply by email." },
        ["support_reply"] = new[] { "Ответ поддержки", "Відповідь підтримки", "Support reply" },
        ["theme_toggle"] = new[] { "Тема", "Тема", "Theme" },
        ["theme_dark"] = new[] { "Тёмная", "Темна", "Dark" },
        ["theme_light"] = new[] { "Светлая", "Світла", "Light" },
        ["admin_dashboard"] = new[] { "Панель администратора", "Панель адміністратора", "Admin dashboard" },
        ["admin_games"] = new[] { "Игры", "Ігри", "Games" },
        ["admin_users"] = new[] { "Пользователи", "Користувачі", "Users" },
        ["admin_tickets"] = new[] { "Обращения", "Звернення", "Tickets" },
        ["admin_add_game"] = new[] { "Добавить игру", "Додати гру", "Add game" },
        ["admin_edit"] = new[] { "Редактировать", "Редагувати", "Edit" },
        ["admin_delete"] = new[] { "Удалить", "Видалити", "Delete" },
        ["admin_save"] = new[] { "Сохранить", "Зберегти", "Save" },
        ["admin_block"] = new[] { "Заблокировать", "Заблокувати", "Block" },
        ["admin_unblock"] = new[] { "Разблокировать", "Розблокувати", "Unblock" },
        ["admin_reply"] = new[] { "Ответить", "Відповісти", "Reply" },
        ["admin_send_reply"] = new[] { "Отправить ответ", "Надіслати відповідь", "Send reply" },
        ["admin_no_tickets"] = new[] { "Обращений пока нет.", "Звернень поки немає.", "No tickets yet." },
        ["back"] = new[] { "Назад", "Назад", "Back" },
        ["footer_rights"] = new[] { "Все права защищены. Все торговые марки являются собственностью соответствующих владельцев.", "Усі права захищено. Усі торговельні марки є власністю відповідних власників.", "All rights reserved. All trademarks are the property of their respective owners." },
        ["footer_terms"] = new[] { "Условия использования", "Умови використання", "Terms of Use" },
        ["footer_careers"] = new[] { "Вакансии", "Вакансії", "Careers" },
        ["footer_privacy"] = new[] { "Политика конфиденциальности", "Політика конфіденційності", "Privacy" },
        ["footer_contacts"] = new[] { "Контакты", "Контакти", "Contact" },
        ["footer_gift_cards"] = new[] { "Подарочные карты", "Подарункові картки", "Gift cards" },
        ["home_all_genres"] = new[] { "Все", "Усі", "All" },
        ["account_help_login"] = new[] { "Помощь, не могу войти", "Допомога, не можу увійти", "Help, I can't sign in" },
        ["account_demo"] = new[] { "Демо-аккаунт", "Демоакаунт", "Demo account" },
        ["account_qr_login"] = new[] { "Войти по QR", "Увійти за QR-кодом", "Sign in with QR" },
        ["account_qr_instructions"] = new[] { "Откройте приложение на телефоне или используйте другой браузер, чтобы отсканировать QR-код. После подтверждения этот браузер автоматически выполнит вход.", "Відкрийте застосунок на телефоні або інший браузер, щоб відсканувати QR-код. Після підтвердження цей браузер автоматично виконає вхід.", "Open the app on your phone or use another browser to scan the QR code. After confirmation, this browser will sign in automatically." },
        ["account_qr_confirmed"] = new[] { "Подтверждено, выполняем вход...", "Підтверджено, виконуємо вхід...", "Confirmed. Signing in..." },
        ["account_qr_failed"] = new[] { "Автоматический вход не удался", "Не вдалося виконати автоматичний вхід", "Automatic sign-in failed" },
        ["account_qr_confirm_title"] = new[] { "Подтвердите вход", "Підтвердьте вхід", "Confirm sign-in" },
        ["account_qr_confirm_btn"] = new[] { "Подтвердить", "Підтвердити", "Confirm" },
        ["account_qr_confirm_text"] = new[] { "Введите данные аккаунта, чтобы подтвердить вход на другом устройстве.", "Введіть дані акаунта, щоб підтвердити вхід на іншому пристрої.", "Enter your account details to confirm sign-in on another device." },
        ["account_achievements_received"] = new[] { "Получено достижений", "Отримано досягнень", "Achievements earned" },
        ["account_no_achievements"] = new[] { "Пока нет достижений.", "Поки немає досягнень.", "No achievements yet." },
        ["account_played"] = new[] { "Наиграно", "Награно", "Played" },
        ["profile_level_value"] = new[] { "Уровень", "Рівень", "Level" },
        ["profile_empty_achievements"] = new[] { "Пока нет достижений.", "Поки немає досягнень.", "No achievements yet." },
        ["cart_title_mine"] = new[] { "Моя корзина", "Мій кошик", "My cart" },
        ["wishlist_title_mine"] = new[] { "Мой список желаемого", "Мій список бажань", "My wishlist" },
        ["wishlist_empty_text"] = new[] { "Список пуст.", "Список порожній.", "Your wishlist is empty." },
        ["wishlist_added_at"] = new[] { "Добавлено", "Додано", "Added" },
        ["game_genre"] = new[] { "Жанр", "Жанр", "Genre" },
        ["game_developer"] = new[] { "Разработчик", "Розробник", "Developer" },
        ["game_publisher"] = new[] { "Издатель", "Видавець", "Publisher" },
        ["game_release_date"] = new[] { "Дата выхода", "Дата виходу", "Release date" },
        ["game_review_count"] = new[] { "Отзывы", "Відгуки", "Reviews" },
        ["game_review_summary"] = new[] { "Обзоры", "Огляди", "Reviews" },
        ["game_review_placeholder"] = new[] { "Напишите отзыв об игре", "Напишіть відгук про гру", "Write a review" },
        ["game_recommends"] = new[] { "Рекомендует", "Рекомендує", "Recommends" },
        ["game_does_not_recommend"] = new[] { "Не рекомендует", "Не рекомендує", "Does not recommend" },
        ["game_achievement_percent"] = new[] { "Получили", "Отримали", "Earned by" },
        ["admin_orders"] = new[] { "Заказы", "Замовлення", "Orders" },
        ["admin_revenue"] = new[] { "Выручка", "Дохід", "Revenue" },
        ["admin_delete_game_confirm"] = new[] { "Удалить игру?", "Видалити гру?", "Delete this game?" },
        ["admin_blocked"] = new[] { "Заблокирован", "Заблокований", "Blocked" },
        ["admin_game_title"] = new[] { "Название", "Назва", "Title" },
        ["admin_description"] = new[] { "Описание", "Опис", "Description" },
        ["admin_developer"] = new[] { "Разработчик", "Розробник", "Developer" },
        ["admin_publisher"] = new[] { "Издатель", "Видавець", "Publisher" },
        ["admin_genre"] = new[] { "Жанр", "Жанр", "Genre" },
        ["admin_release_date"] = new[] { "Дата выхода", "Дата виходу", "Release date" },
        ["admin_price"] = new[] { "Цена, $", "Ціна, $", "Price, $" },
        ["admin_discount"] = new[] { "Скидка, %", "Знижка, %", "Discount, %" },
        ["admin_age_rating"] = new[] { "Возрастной рейтинг", "Віковий рейтинг", "Age rating" },
        ["admin_featured"] = new[] { "Показывать в рекомендуемых", "Показувати серед рекомендованих", "Show in featured" },
        ["admin_cover_color_from"] = new[] { "Цвет обложки (от)", "Колір обкладинки (від)", "Cover color (from)" },
        ["admin_cover_color_to"] = new[] { "Цвет обложки (до)", "Колір обкладинки (до)", "Cover color (to)" },
        ["admin_min_requirements"] = new[] { "Минимальные требования (через |)", "Мінімальні вимоги (через |)", "Minimum requirements (separated by |)" },
        ["admin_rec_requirements"] = new[] { "Рекомендуемые требования (через |)", "Рекомендовані вимоги (через |)", "Recommended requirements (separated by |)" },
        ["checkout_card_number_placeholder"] = new[] { "Номер карты", "Номер картки", "Card number" },
        ["checkout_cardholder"] = new[] { "Имя владельца", "Ім'я власника", "Cardholder name" },
        ["checkout_order_total"] = new[] { "Ваш заказ", "Ваше замовлення", "Your order" },
        ["success_purchase_title"] = new[] { "Спасибо за покупку!", "Дякуємо за покупку!", "Thanks for your purchase!" },
        ["success_purchase_text"] = new[] { "Игры добавлены в вашу библиотеку.", "Ігри додано до вашої бібліотеки.", "The games were added to your library." },
        ["footer_news_title"] = new[] { "V Store — Обзор", "V Store — Огляд", "V Store — Store" },
        ["admin_status_blocked"] = new[] { "Заблокирован", "Заблокований", "Blocked" },
        ["admin_currency_note"] = new[] { "Цена, $", "Ціна, $", "Price, $" },
        ["login_invalid"] = new[] { "Неверное имя аккаунта или пароль", "Неправильне ім'я акаунта або пароль", "Invalid account name or password" },
        ["login_blocked"] = new[] { "Этот аккаунт заблокирован администрацией", "Цей акаунт заблоковано адміністрацією", "This account has been blocked by an administrator" },
        ["login_help_title"] = new[] { "Помощь, не могу войти", "Допомога, не можу увійти", "Help, I can't sign in" },
        ["news_title_page"] = new[] { "Новости", "Новини", "News" },
        ["news_title_current"] = new[] { "Актуальные новости", "Актуальні новини", "Latest news" },
        ["checkout_expiry_format"] = new[] { "ММ/ГГ", "ММ/РР", "MM/YY" },
        ["checkout_title_full"] = new[] { "Оформление заказа", "Оформлення замовлення", "Checkout" },
        ["ticket_open"] = new[] { "Открыто", "Відкрито", "Open" },
        ["ticket_answered"] = new[] { "Отвечено", "Відповіли", "Answered" },
        ["google_login_failed"] = new[] { "Не удалось войти через Google", "Не вдалося увійти через Google", "Could not sign in with Google" },
        ["forgot_user_not_found"] = new[] { "Пользователь с такой почтой не найден", "Користувача з такою поштою не знайдено", "No user found with that email" },
        ["email_send_failed"] = new[] { "Не удалось отправить письмо. Попробуйте позже.", "Не вдалося надіслати листа. Спробуйте пізніше.", "Could not send the email. Please try again later." },
        ["password_too_short"] = new[] { "Пароль должен содержать минимум 6 символов", "Пароль має містити щонайменше 6 символів", "Password must be at least 6 characters long" },
        ["email_already_used"] = new[] { "Пользователь с такой почтой уже существует", "Користувач із такою поштою вже існує", "An account with this email already exists" },
        ["nickname_already_used"] = new[] { "Это игровое имя уже занято", "Це ігрове ім'я вже зайняте", "This nickname is already taken" },
        ["card_number_invalid"] = new[] { "Введите 16 цифр номера карты", "Введіть 16 цифр номера картки", "Enter the 16-digit card number" },
        ["card_holder_required"] = new[] { "Введите имя владельца карты", "Введіть ім'я власника картки", "Enter the cardholder name" },
        ["card_expiry_invalid"] = new[] { "Укажите срок действия в формате ММ/ГГ", "Укажіть термін дії у форматі ММ/РР", "Enter the expiry date in MM/YY format" },
        ["card_cvv_invalid"] = new[] { "Введите 3 цифры CVV", "Введіть 3 цифри CVV", "Enter the 3-digit CVV" },
        ["review_summary_none"] = new[] { "Нет отзывов", "Немає відгуків", "No reviews" },
        ["review_summary_very_positive"] = new[] { "Очень положительные", "Дуже позитивні", "Very positive" },
        ["review_summary_mostly_positive"] = new[] { "В основном положительные", "Переважно позитивні", "Mostly positive" },
        ["review_summary_mixed"] = new[] { "Смешанные", "Змішані", "Mixed" },
        ["review_summary_mostly_negative"] = new[] { "В основном отрицательные", "Переважно негативні", "Mostly negative" },
        ["validation_nickname_required"] = new[] { "Введите игровое имя", "Введіть ігрове ім'я", "Enter a nickname" },
        ["validation_nickname_length"] = new[] { "Имя должно содержать от 3 до 30 символов", "Ім'я має містити від 3 до 30 символів", "Name must be between 3 and 30 characters" },
        ["validation_email_required"] = new[] { "Введите почту", "Введіть електронну пошту", "Enter an email address" },
        ["validation_email_invalid"] = new[] { "Некорректный адрес почты", "Некоректна адреса електронної пошти", "Enter a valid email address" },
        ["validation_password_required"] = new[] { "Введите пароль", "Введіть пароль", "Enter a password" },
        ["validation_terms_required"] = new[] { "Необходимо принять условия соглашения", "Потрібно прийняти умови угоди", "You must accept the agreement" },
        ["validation_login_required"] = new[] { "Введите имя аккаунта или почту", "Введіть ім'я акаунта або пошту", "Enter your account name or email" },
        ["validation_title_required"] = new[] { "Введите название", "Введіть назву", "Enter a title" },
        ["validation_description_required"] = new[] { "Введите описание", "Введіть опис", "Enter a description" },
        ["validation_developer_required"] = new[] { "Введите разработчика", "Введіть розробника", "Enter a developer" },
        ["validation_publisher_required"] = new[] { "Введите издателя", "Введіть видавця", "Enter a publisher" },
        ["validation_genre_required"] = new[] { "Введите жанр", "Введіть жанр", "Enter a genre" },
        ["validation_release_date_required"] = new[] { "Укажите дату выхода", "Укажіть дату виходу", "Enter a release date" },
        ["validation_price_invalid"] = new[] { "Некорректная цена", "Некоректна ціна", "Invalid price" },
        ["validation_discount_invalid"] = new[] { "Скидка должна быть от 0 до 100%", "Знижка має бути від 0 до 100%", "Discount must be between 0 and 100%" },
        ["validation_age_rating_invalid"] = new[] { "Некорректный возрастной рейтинг", "Некоректний віковий рейтинг", "Invalid age rating" },
        ["validation_name_required"] = new[] { "Введите имя", "Введіть ім'я", "Enter a name" },
        ["validation_subject_required"] = new[] { "Введите тему обращения", "Введіть тему звернення", "Enter a subject" },
        ["validation_message_required"] = new[] { "Введите сообщение", "Введіть повідомлення", "Enter a message" },
    };
}
